### ISSUE TITLE
FCD disk remove operation fails

### ISSUE THREAD

**Issue by kannankavappan** [vmware/safekeeping#1]
vmbk#  ivd -list

Connecting...
Connected to Platform Service Controller: https://fcdvc101vapp.fmr.com/sts/STSService
LookupService reports 1 VimService Instance
Connected to VimService uuid: ddf67b17-fb54-446d-94ee-1c7ebff6adba url: https://fcdvc101vapp.fmr.com:443/sdk
        VMware vCenter Server 6.7.0 build-15129973 - Api Version: 6.7.3
Connected to Storage Profile Service Ver.2.0 url: https://fcdvc101vapp.fmr.com/pbm
Connected to VMware Virtual Storage Lifecycle Manager Service 1.0.0 url: https://fcdvc101vapp.fmr.com/vslm/sdk
Connected to Vapi Service url: https://fcdvc101vapp.fmr.com/api
entity  uuid                                    name                                 size         cbt   snapshot    attached               datastore    path
ivd     06197122-4f0a-4922-b9ab-f6e8f2d17fa7    ivddisk2                              1024MB    false         no         yes              datastore1    fcd/7932c62e061e4c44834d96a316964587.vmdk
ivd     e7879fcd-2cd9-424e-ab20-6b5f21f9a1e7    ivddisk1                              2048MB    false         no         yes              datastore1    fcd/1dbe0fa82dd2487688c4fddcfc8f4591.vmdk
vmbk#
vmbk#
vmbk#  ivd -remove ivd:e7879fcd-2cd9-424e-ab20-6b5f21f9a1e7
Destroy ivd: ivd     e7879fcd-2cd9-424e-ab20-6b5f21f9a1e7       ivddisk1
Confirm the operation (y/n)? y
Destroy Improved Virtual Disks  ivddisk1 fails
vmbk#
vmbk#

I have created 2 new FCD disks. One observation is, it shows attached by default. Actually the disks are not attached to any VM.

**Comment by mdaneri** [comment]
Can you post the log error? please run the **reconcile** command and retry?

**Comment by kannankavappan** [comment]
Thanks for looking into this issue. 

vmbk#  ivd -reconcile -datastore datastore1
Starting reconciliation for datastore:datastore1
Done

vmbk#  ivd -list
entity  uuid                                    name                                 size         cbt   snapshot    attached               datastore    path
ivd     06197122-4f0a-4922-b9ab-f6e8f2d17fa7    ivddisk2                              1024MB    false         no         yes              datastore1    fcd/7932c62e061e4c44834d96a316964587.vmdk
ivd     e7879fcd-2cd9-424e-ab20-6b5f21f9a1e7    ivddisk1                              2048MB    false         no         yes              datastore1    fcd/1dbe0fa82dd2487688c4fddcfc8f4591.vmdk
vmbk#

vmbk#  ivd -remove ivd:ivddisk2
Destroy ivd: ivd     06197122-4f0a-4922-b9ab-f6e8f2d17fa7       ivddisk2
Confirm the operation (y/n)? y
Destroy Improved Virtual Disks  **ivddisk2** fails

**Comment by kannankavappan** [comment]
Error message:

03/02/20 06:56:52.493 [WARNING, 1, Command, showWarning] Destroy Improved Virtual Disks  ivddisk2 fails
03/02/20 06:57:00.948 [WARNING, 1, Command, showWarning] No datastore specified. Use -datastore
03/02/20 06:57:23.706 [INFO, 1, com.vmware.vmbk.soap.VslmConnection, showInfo] Starting reconciliation for datastore:datastore1
03/02/20 06:57:25.422 [INFO, 1, com.vmware.vmbk.soap.VslmConnection, showInfo] Done
03/02/20 06:57:33.474 [INFO, 1, Command, getAnyImprovedVirtualDisk] 1: 06197122-4f0a-4922-b9ab-f6e8f2d17fa7 ivddisk2 Datastore: datastore1 moref:datastore-10
03/02/20 06:57:33.474 [INFO, 1, Command, getAnyImprovedVirtualDisk] 2: e7879fcd-2cd9-424e-ab20-6b5f21f9a1e7 ivddisk1 Datastore: datastore1 moref:datastore-10
03/02/20 06:57:33.474 [INFO, 1, Command, logInfo] No Improved Virtual Disk specified
03/02/20 06:57:33.474 [INFO, 1, Command, showInfo] entity  uuid                                 name                                 size         cbt   snapshot    attached               datastore    path                                 
03/02/20 06:57:33.555 [INFO, 1, Command, showInfo] ivd     06197122-4f0a-4922-b9ab-f6e8f2d17fa7 ivddisk2                              1024MB    false         no         yes              datastore1    fcd/7932c62e061e4c44834d96a316964587.vmdk
03/02/20 06:57:33.632 [INFO, 1, Command, showInfo] ivd     e7879fcd-2cd9-424e-ab20-6b5f21f9a1e7 ivddisk1                              2048MB    false         no         yes              datastore1    fcd/1dbe0fa82dd2487688c4fddcfc8f4591.vmdk
03/02/20 06:57:47.649 [WARNING, 1, com.vmware.vmbk.type.ImprovedVirtuaDisk, destroy] com.sun.xml.internal.ws.fault.ServerSOAPFaultException: Client received SOAP Fault from server:
Error processing attribute "type" with value "VslmVStorageObjectManager"

while parsing MoRef for ManagedObject of type vmodl.ManagedObject
at line 1, column 139

while parsing call information for method DeleteVStorageObject_Task
at line 1, column 94

while parsing SOAP body
at line 1, column 86

while parsing SOAP envelope
at line 1, column 22

while parsing HTTP request for method deleteVStorageObject
on object of type vim.vslm.vcenter.VStorageObjectManager
at line 1, column 0 Please see the server log to find more detail regarding exact cause of the failure.
        at com.sun.xml.internal.ws.fault.SOAP11Fault.getProtocolException(SOAP11Fault.java:178)
        at com.sun.xml.internal.ws.fault.SOAPFaultBuilder.createException(SOAPFaultBuilder.java:124)
        at com.sun.xml.internal.ws.client.sei.StubHandler.readResponse(StubHandler.java:238)
        at com.sun.xml.internal.ws.db.DatabindingImpl.deserializeResponse(DatabindingImpl.java:189)
        at com.sun.xml.internal.ws.db.DatabindingImpl.deserializeResponse(DatabindingImpl.java:276)
        at com.sun.xml.internal.ws.client.sei.SyncMethodHandler.invoke(SyncMethodHandler.java:104)
        at com.sun.xml.internal.ws.client.sei.SyncMethodHandler.invoke(SyncMethodHandler.java:77)
        at com.sun.xml.internal.ws.client.sei.SEIStub.invoke(SEIStub.java:147)
        at com.sun.proxy.$Proxy48.deleteVStorageObjectTask(Unknown Source)
        at com.vmware.vmbk.type.ImprovedVirtuaDisk.destroy(ImprovedVirtuaDisk.java:254)
        at com.vmware.vmbk.command.IvdCommand.action_Remove(IvdCommand.java:650)
        at com.vmware.vmbk.command.IvdCommand.action(IvdCommand.java:112)
        at com.vmware.vmbkCmd.command.IvdCommandInteractive.action(IvdCommandInteractive.java:104)
        at com.vmware.vmbkCmd.VmbkMain.dispatch(VmbkMain.java:260)
        at com.vmware.vmbkCmd.VmbkMain.commandFlow(VmbkMain.java:221)
        at com.vmware.vmbkCmd.VmbkMain.interactive(VmbkMain.java:329)
        at com.vmware.vmbkCmd.VmbkMain.run(VmbkMain.java:419)
        at com.vmware.vmbkCmd.VmbkMain.main(VmbkMain.java:102)

03/02/20 06:57:47.650 [WARNING, 1, Command, showWarning] Destroy Improved Virtual Disks  ivddisk2 fails
03/02/20 06:58:05.250 [WARNING, 1, com.vmware.vmbk.type.ImprovedVirtuaDisk, destroy] com.sun.xml.internal.ws.fault.ServerSOAPFaultException: Client received SOAP Fault from server:
Error processing attribute "type" with value "VslmVStorageObjectManager"

while parsing MoRef for ManagedObject of type vmodl.ManagedObject
at line 1, column 139

while parsing call information for method DeleteVStorageObject_Task
at line 1, column 94

while parsing SOAP body
at line 1, column 86

while parsing SOAP envelope
at line 1, column 22

while parsing HTTP request for method deleteVStorageObject
on object of type vim.vslm.vcenter.VStorageObjectManager
at line 1, column 0 Please see the server log to find more detail regarding exact cause of the failure.
        at com.sun.xml.internal.ws.fault.SOAP11Fault.getProtocolException(SOAP11Fault.java:178)
        at com.sun.xml.internal.ws.fault.SOAPFaultBuilder.createException(SOAPFaultBuilder.java:124)
        at com.sun.xml.internal.ws.client.sei.StubHandler.readResponse(StubHandler.java:238)
        at com.sun.xml.internal.ws.db.DatabindingImpl.deserializeResponse(DatabindingImpl.java:189)
        at com.sun.xml.internal.ws.db.DatabindingImpl.deserializeResponse(DatabindingImpl.java:276)
        at com.sun.xml.internal.ws.client.sei.SyncMethodHandler.invoke(SyncMethodHandler.java:104)
        at com.sun.xml.internal.ws.client.sei.SyncMethodHandler.invoke(SyncMethodHandler.java:77)
        at com.sun.xml.internal.ws.client.sei.SEIStub.invoke(SEIStub.java:147)
        at com.sun.proxy.$Proxy48.deleteVStorageObjectTask(Unknown Source)
        at com.vmware.vmbk.type.ImprovedVirtuaDisk.destroy(ImprovedVirtuaDisk.java:254)
        at com.vmware.vmbk.command.IvdCommand.action_Remove(IvdCommand.java:650)
        at com.vmware.vmbk.command.IvdCommand.action(IvdCommand.java:112)
        at com.vmware.vmbkCmd.command.IvdCommandInteractive.action(IvdCommandInteractive.java:104)
        at com.vmware.vmbkCmd.VmbkMain.dispatch(VmbkMain.java:260)
        at com.vmware.vmbkCmd.VmbkMain.commandFlow(VmbkMain.java:221)
        at com.vmware.vmbkCmd.VmbkMain.interactive(VmbkMain.java:329)
        at com.vmware.vmbkCmd.VmbkMain.run(VmbkMain.java:419)
        at com.vmware.vmbkCmd.VmbkMain.main(VmbkMain.java:102)

03/02/20 06:58:05.250 [WARNING, 1, Command, showWarning] Destroy Improved Virtual Disks  ivddisk1 fails
03/02/20 06:58:15.231 [INFO, 1, com.vmware.vmbk.soap.VslmConnection, showInfo] Starting reconciliation for datastore:datastore1
03/02/20 06:58:16.962 [INFO, 1, com.vmware.vmbk.soap.VslmConnection, showInfo] Done
03/02/20 07:00:12.824 [INFO, 79, jDisklib, Log] VDDK_PhoneHome: Https post URL not provided in VddkVacCurlHttpsPost at 995.
03/02/20 07:00:12.824 [WARNING, 80, jDisklib, Warn] VDDK_PhoneHome: VddkVacPushData : Failed to post data to VC/PH at line 1022.

03/02/20 07:00:12.824 [WARNING, 81, jDisklib, Warn] VDDK_PhoneHome: VddkVacPushSessionData : Failed to push session data at line 1709.

03/02/20 07:00:12.825 [INFO, 82, jDisklib, Log] VDDK_PhoneHome: Https post URL not provided in VddkVacCurlHttpsPost at 995.
03/02/20 07:00:12.826 [WARNING, 83, jDisklib, Warn] VDDK_PhoneHome: VddkVacPushData : Failed to post data to VC/PH at line 1022.

03/02/20 07:00:12.826 [WARNING, 84, jDisklib, Warn] VDDK_PhoneHome: VddkVacPushVendorProductData : Failed to push vendor product data at line 1326.

03/02/20 07:00:12.826 [WARNING, 85, jDisklib, Warn] VDDK_PhoneHome: VddkVacWriteMember : Empty field to serialize for key edition at line 188.

03/02/20 07:00:12.826 [INFO, 86, jDisklib, Log] VDDK_PhoneHome: Https post URL not provided in VddkVacCurlHttpsPost at 995.
03/02/20 07:00:12.826 [WARNING, 87, jDisklib, Warn] VDDK_PhoneHome: VddkVacPushData : Failed to post data to VC/PH at line 1022.

03/02/20 07:00:12.826 [WARNING, 88, jDisklib, Warn] VDDK_PhoneHome: VddkVacPushProductInstanceData : Failed to push product instance data at line 1219.

03/02/20 07:00:12.827 [INFO, 89, jDisklib, Log] VDDK_PhoneHome: Https post URL not provided in VddkVacCurlHttpsPost at 995.
03/02/20 07:00:12.827 [WARNING, 90, jDisklib, Warn] VDDK_PhoneHome: VddkVacPushData : Failed to post data to VC/PH at line 1022.

03/02/20 07:00:12.827 [WARNING, 91, jDisklib, Warn] VDDK_PhoneHome: VddkVacPushEnvironmentData : Failed to push env data at line 1136.

03/02/20 07:00:57.463 [INFO, 18, com.vmware.vmbk.soap.VimConnection, keepAlive] keep alive ddf67b17-fb54-446d-94ee-1c7ebff6adba : Current Time 2020-03-02T12:00:45.811239Z
03/02/20 07:00:57.463 [INFO, 18, com.vmware.vmbk.soap.KeepAlive, keepAlive] keep alive 77424798-43a6-407b-9880-f68fb556b245 : Name PBM  Version 2.0
03/02/20 07:00:57.467 [WARNING, 18, com.vmware.vapi.internal.protocol.client.rpc.http.TrustAllX509TrustManager, warn] Skipped the validation of a certificate chain due to configuration policy. Your connection is not secure!
03/02/20 07:00:57.471 [WARNING, 18, com.vmware.vapi.internal.protocol.client.rpc.http.AllowAllHostnameVerifier, warn] Cannot validate the identity of fcdvc101vapp.fmr.com due to the hostname-verification being disabled. You are susceptible to man-in-the-middle attacks!
03/02/20 07:00:57.504 [INFO, 18, com.vmware.vmbk.soap.helpers.VapiAuthenticationHelper, keepAlive] keep alive  user Administrator@VSPHERE.LOCAL: Creation time java.util.GregorianCalendar[time=1583149245411,areFieldsSet=true,areAllFieldsSet=false,lenient=false,zone=sun.util.calendar.ZoneInfo[id="GMT+00:00",offset=0,dstSavings=0,useDaylight=false,transitions=0,lastRule=null],firstDayOfWeek=1,minimalDaysInFirstWeek=1,ERA=1,YEAR=2020,MONTH=2,WEEK_OF_YEAR=10,WEEK_OF_MONTH=1,DAY_OF_MONTH=2,DAY_OF_YEAR=62,DAY_OF_WEEK=2,DAY_OF_WEEK_IN_MONTH=1,AM_PM=0,HOUR=11,HOUR_OF_DAY=11,MINUTE=40,SECOND=45,MILLISECOND=411,ZONE_OFFSET=0,DST_OFFSET=0] Last Accesst Time java.util.GregorianCalendar[time=1583150445821,areFieldsSet=true,areAllFieldsSet=false,lenient=false,zone=sun.util.calendar.ZoneInfo[id="GMT+00:00",offset=0,dstSavings=0,useDaylight=false,transitions=0,lastRule=null],firstDayOfWeek=1,minimalDaysInFirstWeek=1,ERA=1,YEAR=2020,MONTH=2,WEEK_OF_YEAR=10,WEEK_OF_MONTH=1,DAY_OF_MONTH=2,DAY_OF_YEAR=62,DAY_OF_WEEK=2,DAY_OF_WEEK_IN_MONTH=1,AM_PM=1,HOUR=0,HOUR_OF_DAY=12,MINUTE=0,SECOND=45,MILLISECOND=821,ZONE_OFFSET=0,DST_OFFSET=0]
03/02/20 07:04:15.583 [INFO, 1, com.vmware.vmbk.control.target.FileTarget, finalize] Default finalize
03/02/20 07:04:15.584 [INFO, 18, com.vmware.vmbk.soap.KeepAlive, stop] keep alive stopped
03/02/20 07:04:15.584 [INFO, 1, com.vmware.vmbk.soap.VimConnection, disconnect] disconnecting...
03/02/20 07:04:15.685 [WARNING, 1, com.vmware.vmbk.soap.VslmConnection, disconnect] com.vmware.vslm.RuntimeFaultFaultMsg: The session is not authenticated.
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at com.sun.xml.internal.ws.fault.SOAPFaultBuilder.createException(SOAPFaultBuilder.java:135)
        at com.sun.xml.internal.ws.client.sei.StubHandler.readResponse(StubHandler.java:238)
        at com.sun.xml.internal.ws.db.DatabindingImpl.deserializeResponse(DatabindingImpl.java:189)
        at com.sun.xml.internal.ws.db.DatabindingImpl.deserializeResponse(DatabindingImpl.java:276)
        at com.sun.xml.internal.ws.client.sei.SyncMethodHandler.invoke(SyncMethodHandler.java:104)
        at com.sun.xml.internal.ws.client.sei.SyncMethodHandler.invoke(SyncMethodHandler.java:77)
        at com.sun.xml.internal.ws.client.sei.SEIStub.invoke(SEIStub.java:147)
        at com.sun.proxy.$Proxy50.vslmLogout(Unknown Source)
        at com.vmware.vmbk.soap.VslmConnection.disconnect(VslmConnection.java:332)
        at com.vmware.vmbk.soap.VimConnection.disconnect(VimConnection.java:486)
        at com.vmware.vmbk.soap.ConnectionManager.disconnect(ConnectionManager.java:218)
        at com.vmware.vmbk.soap.ConnectionManager.close(ConnectionManager.java:108)
        at com.vmware.vmbk.control.Vmbk.finalizeApp(Vmbk.java:80)
        at com.vmware.vmbkCmd.VmbkMain.interactive(VmbkMain.java:356)
        at com.vmware.vmbkCmd.VmbkMain.run(VmbkMain.java:419)
        at com.vmware.vmbkCmd.VmbkMain.main(VmbkMain.java:102)

03/02/20 07:04:15.689 [WARNING, 1, com.vmware.vapi.internal.protocol.client.rpc.http.TrustAllX509TrustManager, warn] Skipped the validation of a certificate chain due to configuration policy. Your connection is not secure!
03/02/20 07:04:15.693 [WARNING, 1, com.vmware.vapi.internal.protocol.client.rpc.http.AllowAllHostnameVerifier, warn] Cannot validate the identity of fcdvc101vapp.fmr.com due to the hostname-verification being disabled. You are susceptible to man-in-the-middle attacks!
03/02/20 07:04:15.695 [INFO, 1, com.vmware.vmbk.soap.VimConnection, disconnect] disconnected.
03/02/20 07:04:15.695 [INFO, 1, com.vmware.vmbk.soap.PscProvider, disconnect] disconnected.
03/02/20 07:04:15.695 [INFO, 19, com.vmware.vmbk.soap.TokenRenewThread, stop] TokenRenew stopped
03/02/20 07:04:15.696 [INFO, 98, jDisklib, Log] VDDK_PhoneHome: Switching counter index from 0 to 1
03/02/20 07:04:15.699 [INFO, 1, jDisklib, Log] VDDK_PhoneHome: VDDK PhoneHome succeed to exit
03/02/20 07:04:15.700 [INFO, 1, jDisklib, Log] VixDiskLib: VixDiskLib_Exit: Unmatched Init calls so far: 1.
03/02/20 07:04:16.700 [INFO, 1, jDisklib, Log] VixDiskLibVim: VixDiskLibVim_Exit: Clean up.
03/02/20 07:04:16.704 [INFO, 1, com.vmware.vmbk.control.Jvddk, logInfo] Deleting vddk temporary dir:/tmp/vmware-root
03/02/20 07:04:16.704 [INFO, 1, com.vmware.vmbk.control.target.FileTarget, finalize] Default finalize
03/02/20 07:04:16.704 [INFO, 1, com.vmware.vmbk.control.Jvddk, logInfo] Deleting vddk temporary dir:/tmp/vmware-root

**Comment by mdaneri** [comment]
the fix is on main.
sorry I forgot to close the ticket
