### ISSUE TITLE
archive -check or restore always throws No Valid target specified.

### ISSUE THREAD

**Issue by nbhatti** [vmware/safekeeping#14]
### Describe the bug

Hi, I have a few good backups on S3 but when I try to restore or check any of the archive, I always get

```
-> archive -check vm-1215
No Valid target specified.
```

I can see the archives though
```
vm	       vm-1196	502ad6af-9569-0a82-f7c5-9908be36c4d5	1	15 Mar 2022 19:26:38 GMT	2	15 Aug 2022 16:28:12 GMT 	webserver
```
This also happens with restore no matter what other options I use with that. The logs are not throwing any useful information. Am I missing something here or this has something to do with the backups made with safekeeping-1.0.1 and now trying to restore using safekeeping-2.0.1 and the latest head. Though also tried with safekeeping-1.0.1 gives the same message.

Appreciate any support in this regard.

Thanks.

### Reproduction steps

```bash
Vanilla install with only S3 configured.
```

### Expected behavior

Should be able to restore or check the archive

**Comment by mdaneri** [comment]
Can you please post your configuration file.
Please hide anything confidential

**Comment by nbhatti** [comment]
Sure,
```
#VMBK version 2
#Wed Aug 17 01:17:21 PKT 2022
amazonS3.accessKey=XXXXXXXXXXXXX
amazonS3.active=true
amazonS3.backetName=ylinx-pk
amazonS3.region=ap-southeast-9
amazonS3.secretKey=XXXXXXXXXXXXX\=\=
cmdline.prompt=->
fileStorage.active=false
fileStorage.root=/root/git/safekeeping/safekeeping-cmd/build/install/safekeeping-cmd/archive
filter.resourcePoolFilter=
filter.vmFolderFilter=
global.acceptUntrustedCertificate=true
global.autoConfigureCbt=true
global.connectToVslm=true
global.deleteVddkOnExit=false
global.enableCipher=false
global.enableCompression=true
global.excludeBackupServer=false
global.keystore=keystore.pkcs12
global.keyStorePassword=Y2hhbmdlaXQ\=
global.keyStoreSslCertificateAlias=jetty
global.keyStoreSslCetificatePassword=Y2hhbmdlaXQ\=
global.keyStoreType=pkcs12
global.keyStoreUserCetificateAlias=user
global.maxBlockSizeMb=20
global.maxGetThreadsPool=10
global.maxPostThreadsPool=10
global.nfchostport=902
global.overwriteVddkOnStart=false
global.quisceTimeout=5
global.repository=amazonS3
global.retryOnFailure=true
global.reuseSessionForVddkConnection=true
global.transportFullMode=hotadd
global.transportIncMode=nbdssl
global.transportRestore=hotadd
global.useBase64Passwd=true
global.useQueryAllocatedBlocks=false
global.useQueryAllocatedBlocksForIncremental=false
global.useVssWindows
System=true
global.vddkConfig=vddk.conf
global.vssBackupContext=CTX_AUTO
global.vssBackupType=VSS_BT_COPY
global.vssBootableSystemState=true
global.vssPartialFileSupport=false
pscProvider.nfchostport=902
pscProvider.password=XXXXXXXXXXXXX
pscProvider.pscServer=vsphere.local
pscProvider.ssoTicketLifeExpectancyInSec=3000
pscProvider.username=administrator@vsphere.local
```

**Comment by mdaneri** [comment]
Can you please post the log after the operation?

**Comment by nbhatti** [comment]
Here is 
```
archive -list
08/17/22 03:23:44.835 [INFO, 1, com.vmware.safekeeping.core.control.target.AwsS3Target, getGlobalProfileToByteArray] Get global.json from amazonS3
08/17/22 03:23:45.279 [INFO, 1, com.vmware.safekeeping.cmd.command.ArchiveCommandInteractive, getFcoProfileToByteArray] Get profileVm:502de03f-5ae1-c7e0-85c1-2acc47b0092a/profile.json from amazonS3
08/17/22 03:23:45.546 [INFO, 1, com.vmware.safekeeping.cmd.command.ArchiveCommandInteractive, getFcoProfileToByteArray] Get profileVm:50268182-aed0-eb51-52d2-e96136147f70/profile.json from amazonS3
08/17/22 03:23:45.794 [INFO, 1, com.vmware.safekeeping.cmd.command.ArchiveCommandInteractive, getFcoProfileToByteArray] Get profileVm:5026c52a-d54a-98fe-bb76-4d781b8d981a/profile.json from amazonS3
08/17/22 03:23:46.047 [INFO, 1, com.vmware.safekeeping.cmd.command.ArchiveCommandInteractive, getFcoProfileToByteArray] Get profileVm:50263b42-e6a6-e7ef-2624-247301dc7508/profile.json from amazonS3
08/17/22 03:23:46.289 [INFO, 1, com.vmware.safekeeping.cmd.command.ArchiveCommandInteractive, getFcoProfileToByteArray] Get profileVm:5026c054-7714-ac1c-bb7d-3020f17d7816/profile.json from amazonS3
08/17/22 03:23:46.540 [INFO, 1, com.vmware.safekeeping.cmd.command.ArchiveCommandInteractive, getFcoProfileToByteArray] Get profileVm:5026b48d-8c58-4f99-e628-e0c2f7dfd2f1/profile.json from amazonS3
08/17/22 03:23:46.796 [INFO, 1, com.vmware.safekeeping.cmd.command.ArchiveCommandInteractive, getFcoProfileToByteArray] Get profileVm:502618b3-5f41-0c4d-2f75-9c2de25ad80a/profile.json from amazonS3
08/17/22 03:23:47.046 [INFO, 1, com.vmware.safekeeping.cmd.command.ArchiveCommandInteractive, getFcoProfileToByteArray] Get profileVm:5026f3bd-a2e5-c89e-eb56-05dedb54d91b/profile.json from amazonS3
08/17/22 03:23:47.313 [INFO, 1, com.vmware.safekeeping.cmd.command.ArchiveCommandInteractive, getFcoProfileToByteArray] Get profileVm:50266e96-6296-ec6c-acce-10e2714b1397/profile.json from amazonS3
08/17/22 03:23:47.570 [INFO, 1, com.vmware.safekeeping.cmd.command.ArchiveCommandInteractive, getFcoProfileToByteArray] Get profileVm:502ddcc9-e3d8-586a-f197-409e6326cb16/profile.json from amazonS3
08/17/22 03:23:47.818 [INFO, 1, com.vmware.safekeeping.cmd.command.ArchiveCommandInteractive, getFcoProfileToByteArray] Get profileVm:50265156-4a59-f608-48e7-d24837a8ee4d/profile.json from amazonS3
08/17/22 03:23:48.075 [INFO, 1, com.vmware.safekeeping.cmd.command.ArchiveCommandInteractive, getFcoProfileToByteArray] Get profileVm:502d317c-bc72-fc5d-1d64-8e92f8e18e3a/profile.json from amazonS3
08/17/22 03:23:48.318 [INFO, 1, com.vmware.safekeeping.cmd.command.ArchiveCommandInteractive, getFcoProfileToByteArray] Get profileVm:502d1f73-e1fd-8f7b-8234-5b14809d58f3/profile.json from amazonS3
08/17/22 03:23:48.590 [INFO, 1, com.vmware.safekeeping.cmd.command.ArchiveCommandInteractive, getFcoProfileToByteArray] Get profileVm:502a0f0d-482e-2616-03f8-106c613c425a/profile.json from amazonS3
08/17/22 03:23:48.847 [INFO, 1, com.vmware.safekeeping.cmd.command.ArchiveCommandInteractive, getFcoProfileToByteArray] Get profileVm:50265115-5be0-06a3-49de-237474f4b6ae/profile.json from amazonS3
08/17/22 03:23:49.103 [INFO, 1, com.vmware.safekeeping.cmd.command.ArchiveCommandInteractive, getFcoProfileToByteArray] Get profileVm:5026993d-cd7c-022f-db67-2f2ed681ffa0/profile.json from amazonS3
08/17/22 03:23:49.353 [INFO, 1, com.vmware.safekeeping.cmd.command.ArchiveCommandInteractive, getFcoProfileToByteArray] Get profileVm:50269294-1d32-e632-9809-8052a5318f63/profile.json from amazonS3
08/17/22 03:23:49.604 [INFO, 1, com.vmware.safekeeping.cmd.command.ArchiveCommandInteractive, getFcoProfileToByteArray] Get profileVm:50268701-881b-c8d8-3ddf-401c76a633cb/profile.json from amazonS3
08/17/22 03:23:49.850 [INFO, 1, com.vmware.safekeeping.cmd.command.ArchiveCommandInteractive, getFcoProfileToByteArray] Get profileVm:5026bedc-ff3e-a6ee-4493-f3c13fb04a59/profile.json from amazonS3
08/17/22 03:23:50.102 [INFO, 1, com.vmware.safekeeping.cmd.command.ArchiveCommandInteractive, getFcoProfileToByteArray] Get profileVm:5026d2d4-b243-ae1c-9ee1-551c59e21a0e/profile.json from amazonS3
08/17/22 03:23:50.360 [INFO, 1, com.vmware.safekeeping.cmd.command.ArchiveCommandInteractive, getFcoProfileToByteArray] Get profileVm:50263849-2b47-95cd-8a3c-133b09468867/profile.json from amazonS3
08/17/22 03:23:50.623 [INFO, 1, com.vmware.safekeeping.cmd.command.ArchiveCommandInteractive, getFcoProfileToByteArray] Get profileVm:50261f63-e80e-fac6-78a4-b1d5bc9fd89a/profile.json from amazonS3
08/17/22 03:23:50.880 [INFO, 1, com.vmware.safekeeping.cmd.command.ArchiveCommandInteractive, getFcoProfileToByteArray] Get profileVm:502d10cb-4e04-f7d9-d025-23d6690ec0e0/profile.json from amazonS3
08/17/22 03:23:51.136 [INFO, 1, com.vmware.safekeeping.cmd.command.ArchiveCommandInteractive, getFcoProfileToByteArray] Get profileVm:5026c31d-f9b6-edea-6417-9b47c50f01cb/profile.json from amazonS3
08/17/22 03:23:51.379 [INFO, 1, com.vmware.safekeeping.cmd.command.ArchiveCommandInteractive, getFcoProfileToByteArray] Get profileVm:502d16d8-8754-465c-c258-4a258d06c302/profile.json from amazonS3
08/17/22 03:23:51.631 [INFO, 1, com.vmware.safekeeping.cmd.command.ArchiveCommandInteractive, getFcoProfileToByteArray] Get profileVm:5026ec96-28c6-c320-2cac-3b3fb63dfea5/profile.json from amazonS3
08/17/22 03:23:51.872 [INFO, 1, com.vmware.safekeeping.cmd.command.ArchiveCommandInteractive, getFcoProfileToByteArray] Get profileVm:502db477-174c-6c7c-2a32-79d9865fb1b5/profile.json from amazonS3
08/17/22 03:23:52.137 [INFO, 1, com.vmware.safekeeping.cmd.command.ArchiveCommandInteractive, getFcoProfileToByteArray] Get profileVm:502a5631-86e4-3fb2-3507-e7a7b372d13d/profile.json from amazonS3
08/17/22 03:23:52.376 [INFO, 1, com.vmware.safekeeping.cmd.command.ArchiveCommandInteractive, getFcoProfileToByteArray] Get profileVm:502d7ca3-e45a-5b7e-9c2e-23d9e6e7c5bb/profile.json from amazonS3
08/17/22 03:23:52.630 [INFO, 1, com.vmware.safekeeping.cmd.command.ArchiveCommandInteractive, getFcoProfileToByteArray] Get profileVm:502d10d5-80ca-27d2-77c7-f6da12d8c092/profile.json from amazonS3
08/17/22 03:23:52.908 [INFO, 1, com.vmware.safekeeping.cmd.command.ArchiveCommandInteractive, getFcoProfileToByteArray] Get profileVm:5026439f-db0b-076e-0b8c-1bcf036a0401/profile.json from amazonS3
08/17/22 03:23:53.157 [INFO, 1, com.vmware.safekeeping.cmd.command.ArchiveCommandInteractive, getFcoProfileToByteArray] Get profileVm:5014dfba-e8ac-abd0-abb8-9b1a77488284/profile.json from amazonS3
08/17/22 03:23:53.417 [INFO, 1, com.vmware.safekeeping.cmd.command.ArchiveCommandInteractive, getFcoProfileToByteArray] Get profileVm:502d2ebe-dec4-4d51-4e78-39a5f59754ea/profile.json from amazonS3
08/17/22 03:23:53.661 [INFO, 1, com.vmware.safekeeping.cmd.command.ArchiveCommandInteractive, getFcoProfileToByteArray] Get profileVm:502ad6af-9569-0a82-f7c5-9908be36c4d5/profile.json from amazonS3
08/17/22 03:23:53.910 [INFO, 1, com.vmware.safekeeping.cmd.command.ArchiveCommandInteractive, getFcoProfileToByteArray] Get profileVm:50269fc9-2053-f347-2bef-bf374f5c1550/profile.json from amazonS3
08/17/22 03:23:54.040 [WARNING, 1, com.vmware.safekeeping.core.command.results.AbstractCoreResultActionImpl, progressIncrease] Over 100 100.00
08/17/22 03:23:54.151 [INFO, 1, com.vmware.safekeeping.cmd.command.ArchiveCommandInteractive, getFcoProfileToByteArray] Get profileVm:502d201c-d292-bb76-5e03-c681f5db05b9/profile.json from amazonS3
```
and tried restore
```
restore vm:vm-1196  name "newWebServer" datastore "iSCSI-SAN-R420-2.4TB"
08/17/22 03:32:38.020 [INFO, 1, com.vmware.safekeeping.core.control.target.AwsS3Target, getGlobalProfileToByteArray] Get global.json from amazonS3
08/17/22 03:32:38.240 [WARNING, 1, RestoreCommand, getTargetFcoEntitiesFromRepository] No Virtual Machine with Moref vm-1196=com.vmware.safekeeping.core.type.FcoTarget@4d4fa89d exist on the repository
08/17/22 03:32:38.240 [INFO, 1, RestoreCommand, showInfo] No Valid target specified.
```
but archive -list shows
```
vm	       vm-1196	502ad6af-9569-0a82-f7c5-9908be36c4d5	1	15 Mar 2022 19:26:38 GMT	2	15 Aug 2022 16:28:12 GMT 	yLinx-Webserver
```

But then I just tried 
```
restore vm:502ad6af-9569-0a82-f7c5-9908be36c4d5 -name "newWebServer" -datastore "iSCSI-SAN-R420-2.4TB"
```
With the VM uuid and looks like the restore is working fine now. So if the vm-id is changed, isn't the restore or archive suppose to work?

**Comment by nbhatti** [comment]
and the restore failed with the following
```
08/17/22 03:37:43.494 [INFO, 44, com.vmware.safekeeping.core.command.RestoreCommand, reportResult] (1644/2731)   x       40378368      40402943    12.00MB     54.66KB    0.25s    48.91MB/s   224.8:1     0.22MB/s	CFADD44A103CBD6D5726FA07B27D7AAD2F67ED3930FF96901C486A5BEAF7E723	58C0E9FEA3E5BAB5A23BEF7F04DE3480
08/17/22 03:37:43.506 [INFO, 41, com.vmware.safekeeping.core.command.RestoreCommand, reportResult] (1646/2731)   x       40427520      40452095    12.00MB     54.66KB    0.22s    53.84MB/s   224.8:1     0.24MB/s	CFADD44A103CBD6D5726FA07B27D7AAD2F67ED3930FF96901C486A5BEAF7E723	58C0E9FEA3E5BAB5A23BEF7F04DE3480
08/17/22 03:37:43.518 [INFO, 46, com.vmware.safekeeping.core.command.RestoreCommand, reportResult] (1645/2731)   x       40402944      40427519    12.00MB     54.66KB    0.25s    48.96MB/s   224.8:1     0.22MB/s	CFADD44A103CBD6D5726FA07B27D7AAD2F67ED3930FF96901C486A5BEAF7E723	58C0E9FEA3E5BAB5A23BEF7F04DE3480
08/17/22 03:37:43.521 [WARNING, 39, com.vmware.safekeeping.core.command.RestoreCommand, reportResult] (1649/2731)  FAILED		  12.00MB		 0.11s
	Reason:(vm:yLinx-Webserver uuid:502ad6af-9569-0a82-f7c5-9908be36c4d5 moref:vm-5149) unknow - check the log
08/17/22 03:37:43.521 [WARNING, 39, com.vmware.safekeeping.core.command.RestoreCommand, logWarning] java.lang.NullPointerException
	at com.vmware.safekeeping.core.control.target.AwsS3TargetOperations.openGetDump(AwsS3TargetOperations.java:242)
	at com.vmware.safekeeping.core.core.RestoreThread.run(RestoreThread.java:93)
	at com.vmware.safekeeping.core.core.RestoreThread.call(RestoreThread.java:65)
	at com.vmware.safekeeping.core.core.RestoreThread.call(RestoreThread.java:46)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)

08/17/22 03:37:43.527 [WARNING, 43, com.vmware.safekeeping.core.command.RestoreCommand, reportResult] (1650/2731)  FAILED		  12.00MB		 0.11s
	Reason:(vm:yLinx-Webserver uuid:502ad6af-9569-0a82-f7c5-9908be36c4d5 moref:vm-5149) unknow - check the log
08/17/22 03:37:43.527 [WARNING, 43, com.vmware.safekeeping.core.command.RestoreCommand, logWarning] java.lang.NullPointerException
	at com.vmware.safekeeping.core.control.target.AwsS3TargetOperations.openGetDump(AwsS3TargetOperations.java:242)
	at com.vmware.safekeeping.core.core.RestoreThread.run(RestoreThread.java:93)
	at com.vmware.safekeeping.core.core.RestoreThread.call(RestoreThread.java:65)
	at com.vmware.safekeeping.core.core.RestoreThread.call(RestoreThread.java:46)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)

08/17/22 03:37:43.558 [WARNING, 47, com.vmware.safekeeping.core.command.RestoreCommand, reportResult] (1651/2731)  FAILED		  12.00MB		 0.11s
	Reason:(vm:yLinx-Webserver uuid:502ad6af-9569-0a82-f7c5-9908be36c4d5 moref:vm-5149) unknow - check the log
08/17/22 03:37:43.559 [WARNING, 47, com.vmware.safekeeping.core.command.RestoreCommand, logWarning] java.lang.NullPointerException
	at com.vmware.safekeeping.core.control.target.AwsS3TargetOperations.openGetDump(AwsS3TargetOperations.java:242)
	at com.vmware.safekeeping.core.core.RestoreThread.run(RestoreThread.java:93)
	at com.vmware.safekeeping.core.core.RestoreThread.call(RestoreThread.java:65)
	at com.vmware.safekeeping.core.core.RestoreThread.call(RestoreThread.java:46)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)

08/17/22 03:37:43.576 [WARNING, 45, com.vmware.safekeeping.core.command.RestoreCommand, reportResult] (1652/2731)  FAILED		  12.00MB		 0.11s
	Reason:(vm:yLinx-Webserver uuid:502ad6af-9569-0a82-f7c5-9908be36c4d5 moref:vm-5149) unknow - check the log
08/17/22 03:37:43.576 [WARNING, 45, com.vmware.safekeeping.core.command.RestoreCommand, logWarning] java.lang.NullPointerException
	at com.vmware.safekeeping.core.control.target.AwsS3TargetOperations.openGetDump(AwsS3TargetOperations.java:242)
	at com.vmware.safekeeping.core.core.RestoreThread.run(RestoreThread.java:93)
	at com.vmware.safekeeping.core.core.RestoreThread.call(RestoreThread.java:65)
	at com.vmware.safekeeping.core.core.RestoreThread.call(RestoreThread.java:46)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)

08/17/22 03:37:43.578 [WARNING, 38, com.vmware.safekeeping.core.command.RestoreCommand, restoreAndConsolidateThreads] Operation disk:0 block:1646 - fails - see log for more details
08/17/22 03:37:43.583 [INFO, 18, jDisklib, Log] VixDiskLib: VixDiskLib_Close: Close disk.
```

**Comment by mdaneri** [comment]
looks like one of the incremental block has an issue. 
Version 2 and 1 are not really compatible or at least I never tried the compatibility aspect. 
you have 15 generations (backup) from this VM can you try to run a restore specifying an old generation (incremental backup)

**Comment by mdaneri** [comment]
something is wrong.
```
08/17/22 03:37:43.494 [INFO, 44, com.vmware.safekeeping.core.command.RestoreCommand, reportResult] (1644/2731)   x       40378368      40402943    12.00MB     54.66KB    0.25s    48.91MB/s   224.8:1     0.22MB/s	CFADD44A103CBD6D5726FA07B27D7AAD2F67ED3930FF96901C486A5BEAF7E723	58C0E9FEA3E5BAB5A23BEF7F04DE3480
08/17/22 03:37:43.506 [INFO, 41, com.vmware.safekeeping.core.command.RestoreCommand, reportResult] (1646/2731)   x       40427520      40452095    12.00MB     54.66KB    0.22s    53.84MB/s   224.8:1     0.24MB/s	CFADD44A103CBD6D5726FA07B27D7AAD2F67ED3930FF96901C486A5BEAF7E723	58C0E9FEA3E5BAB5A23BEF7F04DE3480
08/17/22 03:37:43.518 [INFO, 46, com.vmware.safekeeping.core.command.RestoreCommand, reportResult] (1645/2731)   x       40402944      40427519    12.00MB     54.66KB    0.25s    48.96MB/s   224.8:1     0.22MB/s	CFADD44A103CBD6D5726FA07B27D7AAD2F67ED3930FF96901C486A5BEAF7E723	58C0E9FEA3E5BAB5A23BEF7F04DE3480
```

all those blocks have the same MD5 and SHA2

**Comment by nbhatti** [comment]
I was able to restore generation 0 got the data I needed, but anything above that does not restores. Your catch is correct, could be a bug or the famous the disk locking issue which I was never able to resolve either. I'll open another issue for that but thanks for pointing out the MD5 thing. Appreciate that :-)
